<a href="https://colab.research.google.com/github/Srihitha-M/NASSCOM/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# arange(): Creates numbers in a given range

arr = np.arange(0, 10, 2)

print("Array using arange():", arr)

Array using arange(): [0 2 4 6 8]


In [3]:
# linspace(): Creates evenly spaced values

arr = np.linspace(0, 1, 5)

print("Array using linspace():", arr)

Array using linspace(): [0.   0.25 0.5  0.75 1.  ]


In [4]:
print("Zeros:")
print(np.zeros((2,3)))

print("\nOnes:")
print(np.ones((3,2)))

print("\nIdentity Matrix:")
print(np.eye(3))

print("\nFull Array:")
print(np.full((2,2), 7))

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Full Array:
[[7 7]
 [7 7]]


In [5]:
data = np.array([[5,8,9],
                 [2,4,6]])

print("Data:\n", data)

print("Sum:", np.sum(data))
print("Column-wise Sum:", np.sum(data, axis=0))
print("Row-wise Mean:", np.mean(data, axis=1))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))
print("Standard Deviation:", np.std(data))
print("Index of Maximum:", np.argmax(data))

Data:
 [[5 8 9]
 [2 4 6]]
Sum: 34
Column-wise Sum: [ 7 12 15]
Row-wise Mean: [7.33333333 4.        ]
Maximum: 9
Minimum: 2
Standard Deviation: 2.3570226039551585
Index of Maximum: 2


In [6]:
arr = np.array([3,1,7,2,9])

print("Original:", arr)

sorted_arr = np.sort(arr)

print("Sorted:", sorted_arr)

Original: [3 1 7 2 9]
Sorted: [1 2 3 7 9]


In [7]:
arr = np.array([3,1,7,2,9])

index = np.where(arr > 4)

print("Indices:", index)
print("Values:", arr[index])

Indices: (array([2, 4]),)
Values: [7 9]


In [8]:
arr = np.arange(1,10)

matrix = arr.reshape(3,3)

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
matrix = np.arange(1,10).reshape(3,3)

print("Original Matrix:")
print(matrix)

print("\nFlattened Array:")
print(matrix.flatten())

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened Array:
[1 2 3 4 5 6 7 8 9]


In [10]:
A = np.array([[1,2],
              [3,4]])

B = np.array([10,20])

print("Matrix A:")
print(A)

print("\nVector B:")
print(B)

print("\nBroadcasted Result:")
print(A + B)

Matrix A:
[[1 2]
 [3 4]]

Vector B:
[10 20]

Broadcasted Result:
[[11 22]
 [13 24]]


In [11]:
nums = np.array([1,2,3,4,5])

mask = nums > 3

print(mask)

print(nums[mask])

[False False False  True  True]
[4 5]


In [12]:
nums = np.array([1,2,3,4,5,6])

result = np.where(nums % 2 == 0, "Even", "Odd")

print(result)

['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [13]:
arr = np.array([10,20,30])

view = arr[:]

view[0] = 99

print("Original:", arr)
print("View:", view)

Original: [99 20 30]
View: [99 20 30]


In [14]:
arr = np.array([10,20,30])

copy = arr.copy()

copy[0] = 55

print("Original:", arr)
print("Copy:", copy)

Original: [10 20 30]
Copy: [55 20 30]


In [15]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(np.vstack((x,y)))

[[1 2 3]
 [4 5 6]]


In [16]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(np.hstack((x,y)))

[1 2 3 4 5 6]


In [17]:
arr = np.arange(10)

parts = np.array_split(arr,3)

print(parts)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [18]:
arr = np.array([10,20,30,40,50,60])

print("First Element:", arr[0])
print("Last Element:", arr[-1])

First Element: 10
Last Element: 60


In [19]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])
print(arr[::2])
print(arr[::-1])

[20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [20]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Matrix:")
print(matrix)

print("Element (1,2):", matrix[1,2])
print("First Row:", matrix[0,:])
print("Second Column:", matrix[:,1])
print("Top Left 2x2:")
print(matrix[:2,:2])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element (1,2): 6
First Row: [1 2 3]
Second Column: [2 5 8]
Top Left 2x2:
[[1 2]
 [4 5]]


In [21]:
arr = np.array([5,10,15,20,25,30])

mask = arr > 15

print("Mask:", mask)

print("Filtered Values:", arr[mask])

Mask: [False False False  True  True  True]
Filtered Values: [20 25 30]


In [22]:
arr = np.array([5,10,15,20,25,30])

result = arr[(arr > 10) & (arr % 2 == 0)]

print(result)

[20 30]


In [23]:
arr = np.array([10,20,30,40,50])

indices = [0,2,4]

print(arr[indices])

[10 30 50]
